[package]
name = "teleop-grpc-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.6"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
prost = "0.9"
r2r = "0.6.0"


[build-dependencies]
tonic-build = "0.6"
